apiVersion: v1
kind: Service
metadata:
  name: api-pedelogo-service
spec:
  selector:
    app: api-pedelogo
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: LoadBalancer